### ISSUE TITLE
make flattr button movable to addon bar

### ISSUE THREAD

**Issue by geier** [flattr/fx-flattr-addon#1]
please make the flattr button movable to the addon bar, since vimperator etc. users cannot normally see it, if it's hidden in the url bar

**Comment by voxpelli** [comment]
I don't think a lot of stuff currently in this add-on would be reusable in such an implementation - the entire add-on was built with the urlbar in mind - so question is if it would make sense to add such a behavior to this add-on or if it would make more sense to solve it another way.

Overall Mozilla and their add-on SDK, which this add-on is built with, is moving away from the add-on bar to instead utilize the urlbar and toolbars - it was supposed to be done last quarter but has been moved ahead to this quarter: https://wiki.mozilla.org/Features/Jetpack/Addons_In_Toolbar Once urlbar support is in the SDK I think it would make sense to try and move away from the custom solution used in this add-on and perhaps that will make it easier to use with eg. vimperator as it would be a more generic implementation.

**Comment by geier** [comment]
ok, thanks for the heads up
keep up the great work anyway
